ID%s: repository(owner: "%s", name: "%s") { 
  stargazerCount
  description
  owner { login }
  name
  url
  repositoryTopics(first: 20) {
    nodes {
      topic {
        name
      }
    }
  }
  defaultBranchRef {
    target {
      ... on Commit {
        committedDate
      }
    }
  }
}

