query {
  search(query: "%s", type: REPOSITORY, first: %s, after: "%s") {
    edges {
      node {
        ... on Repository {
          name
          createdAt
          isArchived
          owner {
            login
          }
          description
          url
          stargazerCount
          repositoryTopics(first: 20) {
            nodes {
              topic {
                name
              }
            }
          }
          defaultBranchRef {
            target {
              ... on Commit {
                committedDate
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
  rateLimit {
    cost
    remaining
  }
}
