CREATE TABLE categories (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

--;;

CREATE TABLE plugins (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category_id INTEGER REFERENCES categories(id),
  repo TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT NOT NULL
);
